const express = require ("express")
const app = express ()
const cors = require ("cors")
app.use(express.json())
app.use(cors())
const songRoutes = require ("./routes/songRoutes")
const churches = require ("./routes/churches")
const audio = require ("./routes/audio")
const lyrics= require ("./routes/lyrics")
const uploader = require ("./routes/churches")
app.use("/songs",songRoutes)
app.use("/churches",churches)
app.use("/uploads",audio)
app.use("/",uploader)
app.use("/uploads",lyrics)
app.use("/songs/:id/audio",audio)
app.use("/songs/:id/lyrics",lyrics)
module.exports= app